### ISSUE TITLE
crosslink_group.c:139: warning: ‘ctr’ may be used uninitialized in this function

### ISSUE THREAD

**Issue by xiekunwhy** [eastmallingresearch/crosslink#1]
Hi,

I tried to compile crosslink in CentOS release 6.7 system, but it gave me some warning like following, are these have some negative  impact on the performance of crosslink?
crosslink_group.c: In function ‘fix_marker_types’:
crosslink_group.c:139: warning: ‘ctr’ may be used uninitialized in this function

Best wishes,
Kun

**Comment by robertvi** [comment]
Hi Kun, no that type of warning should be harmless. In this case the for loop at crosslink_group.c:186 will always initialise the ctr on the first loop, but the compiler is not smart enough to work this out, so it issues a warning as a precaution.
Cheers,
Rob

**Comment by xiekunwhy** [comment]
Hi Rob,
Thank you for your reply.
Cheers,
Kun
